name: Enviar Mensagem Telegram

on:
  workflow_dispatch:  # Permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install requests

      - name: Verificar variável de ambiente
        run: echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}"  # Testa se a variável existe (não imprime o valor)

      - name: Executar o script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Passa o token como variável de ambiente
        run: python enviar_mensagem.py
